on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
  load_test:
    needs: build
    runs-on: self-hosted
    name: Start a load test
    steps:
      - name: Run test in LoadRunner Cloud
        uses: MicroFocus/lrc-gh-action@v1
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: ${{secrets.LRC_CLIENT_ID_PROD}}
          LRC_CLIENT_SECRET: ${{secrets.LRC_CLIENT_SECRET_PROD}}
        with:
          lrc_server: 'https://loadrunner-cloud.saas.microfocus.com'
          lrc_tenant: '142725770'
          lrc_project: '5'
          lrc_test_id: '148'  
          lrc_output_dir: './lrc_report'
          lrc_report_types: 'pdf, csv'
      - name: Get the output runId
        if: always()
        run: echo "LRC Run ID is ${{ steps.lrc_run_test.outputs.lrc_run_id }}"
      - name: upload lrc report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lrc-report-${{ steps.lrc_run_test.outputs.lrc_run_id }}
          path: './lrc_report'
